const CMR='https://cmr.earthdata.nasa.gov/search';
const GQL='https://graphql.earthdata.nasa.gov/api';
const OPENAQ='https://api.openaq.org/v3';
const S={token:sessionStorage.getItem('earthToken')||'',aq:sessionStorage.getItem('openAqKey')||'',verified:false,search:null,collections:[],selected:new Set(),granules:[],rows:[],ground:[],manifest:[]};
const $=id=>document.getElementById(id);
const E={earthToken:$('earthToken'),openAqKey:$('openAqKey'),verifyTokenBtn:$('verifyTokenBtn'),forgetSecretsBtn:$('forgetSecretsBtn'),tokenBadge:$('tokenBadge'),verifyStatus:$('verifyStatus'),component:$('component'),startDate:$('startDate'),endDate:$('endDate'),geometryType:$('geometryType'),geometryLabel:$('geometryLabel'),geometryValue:$('geometryValue'),searchBtn:$('searchBtn'),searchStatus:$('searchStatus'),resultsCard:$('resultsCard'),resultSummary:$('resultSummary'),collectionFilter:$('collectionFilter'),collectionResults:$('collectionResults'),selectAllBtn:$('selectAllBtn'),clearAllBtn:$('clearAllBtn'),fetchBtn:$('fetchBtn'),fetchStatus:$('fetchStatus'),downloadsCard:$('downloadsCard'),metrics:$('metrics'),downloadCsvBtn:$('downloadCsvBtn'),downloadManifestBtn:$('downloadManifestBtn'),conversionLog:$('conversionLog'),groundCard:$('groundCard'),groundBtn:$('groundBtn'),groundStatus:$('groundStatus'),groundSummary:$('groundSummary')};
E.earthToken.value=S.token; E.openAqKey.value=S.aq;
function status(el,t,k){el.textContent=t;el.className='status'+(k?' '+k:'')}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function log(t,k){const d=document.createElement('div');d.className='log-line'+(k?' '+k:'');d.textContent='['+new Date().toLocaleTimeString()+'] '+t;E.conversionLog.appendChild(d);E.conversionLog.scrollTop=E.conversionLog.scrollHeight}
function verified(ok,msg){S.verified=ok;E.searchBtn.disabled=!ok;E.tokenBadge.textContent=ok?'Earthdata token verified':'Earthdata token not verified';E.tokenBadge.className='badge '+(ok?'ok':'muted');status(E.verifyStatus,msg||'',ok?'ok':(msg?'error':''))}
async function verify(){const t=E.earthToken.value.trim();if(!t)return verified(false,'Paste an Earthdata bearer token first.');E.verifyTokenBtn.disabled=true;status(E.verifyStatus,'Verifying with NASA CMR GraphQL…');try{const r=await fetch(GQL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify({query:'{ collections { count } }'})});const b=await r.json().catch(()=>({}));if(!r.ok||b.errors)throw new Error((b.errors&&b.errors[0]&&b.errors[0].message)||('HTTP '+r.status));S.token=t;S.aq=E.openAqKey.value.trim();sessionStorage.setItem('earthToken',S.token);if(S.aq)sessionStorage.setItem('openAqKey',S.aq);verified(true,'Verified. Token is stored only for this browser session.')}catch(e){verified(false,'Verification failed: '+e.message)}finally{E.verifyTokenBtn.disabled=false}}
function forget(){sessionStorage.removeItem('earthToken');sessionStorage.removeItem('openAqKey');S.token='';S.aq='';E.earthToken.value='';E.openAqKey.value='';verified(false,'Session credentials cleared.')}
const GH={bbox:['Bounding box: minLon,minLat,maxLon,maxLat','90.30,23.68,90.55,23.90'],polygon:['Polygon: lon1,lat1,lon2,lat2,…','90.30,23.68,90.55,23.68,90.55,23.90,90.30,23.90'],circle:['Circle: centerLon,centerLat,radiusMeters','90.41,23.81,10000'],point:['Point: longitude,latitude','90.41,23.81'],line:['Line: lon1,lat1,lon2,lat2,…','90.30,23.68,90.55,23.90']};
function geomUI(){const h=GH[E.geometryType.value];E.geometryLabel.textContent=h[0];E.geometryValue.placeholder=h[1]}
function nums(s){const a=s.split(/[\\s,;]+/).filter(Boolean).map(Number);if(a.some(x=>!Number.isFinite(x)))throw new Error('Geometry contains a non-numeric value.');return a}
function coord(lon,lat){if(lon<-180||lon>180||lat<-90||lat>90)throw new Error('Invalid coordinate: '+lon+','+lat)}
function geometry(){const type=E.geometryType.value,a=nums(E.geometryValue.value.trim());let v=a.slice(),key=type==='bbox'?'bounding_box':type;if(type==='bbox'){if(a.length!==4)throw new Error('Bounding box needs exactly 4 numbers.');coord(a[0],a[1]);coord(a[2],a[3]);if(a[0]>=a[2]||a[1]>=a[3])throw new Error('Bounding box min values must be lower than max values.')}else if(type==='circle'){if(a.length!==3)throw new Error('Circle needs longitude, latitude and radius in meters.');coord(a[0],a[1]);if(a[2]<=0)throw new Error('Circle radius must be positive.')}else if(type==='point'){if(a.length!==2)throw new Error('Point needs longitude and latitude.');coord(a[0],a[1])}else if(type==='line'){if(a.length<4||a.length%2)throw new Error('Line needs at least two longitude/latitude pairs.');for(let i=0;i<a.length;i+=2)coord(a[i],a[i+1])}else{if(a.length<6||a.length%2)throw new Error('Polygon needs at least three longitude/latitude pairs.');for(let i=0;i<a.length;i+=2)coord(a[i],a[i+1]);if(a[0]!==a[a.length-2]||a[1]!==a[a.length-1])v.push(a[0],a[1])}return{type:type,key:key,values:v,value:v.join(',')}}
function bbox(g){const v=g.values;if(g.type==='bbox')return v;if(g.type==='circle'){const lon=v[0],lat=v[1],r=v[2],dy=r/111320,dx=r/(111320*Math.max(.1,Math.cos(lat*Math.PI/180)));return[lon-dx,lat-dy,lon+dx,lat+dy]}if(g.type==='point')return[v[0]-.02,v[1]-.02,v[0]+.02,v[1]+.02];const xs=[],ys=[];for(let i=0;i<v.length;i+=2){xs.push(v[i]);ys.push(v[i+1])}return[Math.min.apply(null,xs),Math.min.apply(null,ys),Math.max.apply(null,xs),Math.max.apply(null,ys)]}
const isoStart=d=>new Date(d+'T00:00:00Z').toISOString(),isoEnd=d=>new Date(d+'T23:59:59.999Z').toISOString();
function cparams(o){const p=new URLSearchParams();p.set('keyword',o.component);p.set('downloadable','true');p.set('has_granules_or_cwic','true');p.set('page_size',String(o.pageSize||100));p.set(o.geometry.key,o.geometry.value);if(o.temporal!==false){p.set('temporal',isoStart(o.start)+','+isoEnd(o.end));p.set('options[temporal][limit_to_granules]','true')}return p}
async function cmr(path,p){const r=await fetch(CMR+'/'+path+'?'+p.toString(),{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('CMR '+r.status+': '+await r.text().catch(()=>r.statusText));return r.json()}
function col(i,availability){const m=i.meta||{},u=i.umm||{};return{id:m['concept-id']||m.conceptId,shortName:u.ShortName||'Unknown collection',title:u.EntryTitle||u.ShortName||m['native-id']||'Untitled',summary:u.Abstract||u.Purpose||'',provider:m['provider-id']||'',platforms:(u.Platforms||[]).flatMap(p=>[p.ShortName].concat((p.Instruments||[]).map(x=>x.ShortName))).filter(Boolean),availability:availability||'exact',recent:null}}
function gran(i,c){const m=i.meta||{},u=i.umm||{},urls=(u.RelatedUrls||[]).filter(x=>x.URL).map(x=>({url:x.URL,type:x.Type||'',sub:x.Subtype||'',desc:x.Description||''}));const data=urls.filter(x=>/GET DATA|USE SERVICE API/i.test(x.type)&&!/OPENDAP|THREDDS|S3/i.test(x.sub+' '+x.desc));const chosen=data.find(x=>/^https?:/i.test(x.url))||urls.find(x=>/^https?:/i.test(x.url));const r=(u.TemporalExtent&&u.TemporalExtent.RangeDateTime)||{},platforms=(u.Platforms||[]).flatMap(p=>[p.ShortName].concat((p.Instruments||[]).map(x=>x.ShortName))).filter(Boolean);return{id:m['concept-id']||m.conceptId,title:u.GranuleUR||m['native-id']||'granule',start:r.BeginningDateTime||null,end:r.EndingDateTime||r.BeginningDateTime||null,collectionId:c.id,collectionTitle:c.title,collectionShortName:c.shortName,platform:platforms[0]||(c.platforms&&c.platforms[0])||'Unknown',url:chosen&&chosen.url}}
async function granules(c,opt,one,latest){const out=[];for(let page=1;page<=100;page++){const p=new URLSearchParams();p.set('collection_concept_id',c.id);p.set('page_size',one?'1':'2000');p.set('page_num',String(page));p.set(opt.geometry.key,opt.geometry.value);if(latest){p.set('temporal',','+isoEnd(opt.end));p.append('sort_key[]','-start_date')}else p.set('temporal',isoStart(opt.start)+','+isoEnd(opt.end));const d=await cmr('granules.umm_json',p),it=d.items||[];out.push.apply(out,it.map(x=>gran(x,c)));if(one||it.length<2000)break}return out}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let cur=0;async function w(){while(cur<items.length){const i=cur++;try{out[i]=await fn(items[i],i)}catch(e){out[i]={error:e}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},w));return out}
async function search(){if(!S.verified)return;const component=E.component.value.trim(),start=E.startDate.value,end=E.endDate.value;if(!component||!start||!end)return status(E.searchStatus,'Component and both dates are required.','error');if(start>end)return status(E.searchStatus,'Start date cannot be after end date.','error');let g;try{g=geometry()}catch(e){return status(E.searchStatus,e.message,'error')}S.search={component:component,start:start,end:end,geometry:g};S.collections=[];S.selected.clear();E.resultsCard.classList.add('hidden');E.downloadsCard.classList.add('hidden');E.groundCard.classList.add('hidden');E.searchBtn.disabled=true;status(E.searchStatus,'Searching CMR and verifying actual granule availability…');try{const d=await cmr('collections.umm_json',cparams({component:component,start:start,end:end,geometry:g,pageSize:60}));const cand=(d.items||[]).map(x=>col(x,'exact'));const chk=await mapLimit(cand,6,async c=>{const gg=await granules(c,S.search,true,false);return gg.length?Object.assign(c,{preview:gg[0]}):null});let valid=chk.filter(x=>x&&!x.error);if(!valid.length){status(E.searchStatus,'No exact-period granules found. Looking for the nearest prior data…');const fd=await cmr('collections.umm_json',cparams({component:component,start:start,end:end,geometry:g,pageSize:40,temporal:false}));const fc=(fd.items||[]).map(x=>col(x,'fallback'));const rec=await mapLimit(fc,6,async c=>{const gg=await granules(c,S.search,true,true);if(!gg.length)return null;c.recent=gg[0];c.preview=gg[0];return c});valid=rec.filter(x=>x&&!x.error)}S.collections=valid;render();E.resultsCard.classList.remove('hidden');E.groundCard.classList.remove('hidden');const exact=valid.filter(x=>x.availability==='exact').length;E.resultSummary.textContent=valid.length?(valid.length+' collection(s) verified with granules. '+exact+' exact-period, '+(valid.length-exact)+' nearest-prior.'):'No matching granules found for the requested component and area.';status(E.searchStatus,valid.length?'Search complete.':'No usable data found.',valid.length?'ok':'error')}catch(e){status(E.searchStatus,'Search failed: '+e.message,'error')}finally{E.searchBtn.disabled=!S.verified}}
function render(){const q=E.collectionFilter.value.trim().toLowerCase();E.collectionResults.innerHTML='';S.collections.filter(c=>[c.title,c.shortName,c.provider].concat(c.platforms).join(' ').toLowerCase().includes(q)).forEach(c=>{const lab=document.createElement('label');lab.className='collection-item';const b=document.createElement('input');b.type='checkbox';b.checked=S.selected.has(c.id);b.onchange=()=>{b.checked?S.selected.add(c.id):S.selected.delete(c.id);E.fetchBtn.disabled=S.selected.size===0};const info=document.createElement('div'),latest=c.recent&&c.recent.start?new Date(c.recent.start).toISOString().slice(0,10):'';info.innerHTML='<div class="collection-title">'+esc(c.title)+'</div><div class="collection-meta"><span class="pill">'+esc(c.shortName)+'</span><span class="pill">'+esc(c.provider||'NASA provider')+'</span>'+c.platforms.slice(0,3).map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'<span class="pill '+(c.availability==='fallback'?'fallback':'')+'">'+(c.availability==='fallback'?'nearest prior '+esc(latest):'exact date-range data')+'</span></div><div class="collection-desc">'+esc(c.summary||'No collection abstract supplied.')+'</div>';lab.append(b,info);E.collectionResults.appendChild(lab)})}
function cycle(gs,c){const n=(c.shortName+' '+c.title).toLowerCase();if(/hourly|1hr|hour/.test(n))return'hourly';if(/daily|1day|day/.test(n))return'daily';if(/monthly|month/.test(n))return'monthly';if(/yearly|annual|year/.test(n))return'yearly';const t=gs.map(g=>Date.parse(g.start)).filter(Number.isFinite).sort((a,b)=>a-b);if(t.length>1){const d=t.slice(1).map((x,i)=>x-t[i]).sort((a,b)=>a-b)[Math.floor((t.length-1)/2)]/36e5;if(d<=1.5)return'hourly';if(d<=36)return'daily';if(d<=1080)return'monthly';if(d<=10800)return'yearly'}return'granule-based'}
async function fetchSelected(){const sel=S.collections.filter(c=>S.selected.has(c.id));if(!sel.length)return;E.fetchBtn.disabled=true;E.downloadsCard.classList.remove('hidden');E.conversionLog.innerHTML='';S.granules=[];S.rows=[];S.manifest=[];metrics();try{for(let i=0;i<sel.length;i++){const c=sel[i];status(E.fetchStatus,'Crawling '+(i+1)+'/'+sel.length+': '+c.shortName);const fb=c.availability==='fallback';let gs=await granules(c,S.search,false,fb);if(fb&&gs.length){const newest=gs[0].start;gs=gs.filter(g=>g.start===newest)}const cy=cycle(gs,c);gs.forEach(g=>g.dataCycle=cy);S.granules.push.apply(S.granules,gs);log(c.shortName+': '+gs.length+' granule(s) in scope','ok')}S.manifest=S.granules.map(g=>({collection:g.collectionShortName,collection_title:g.collectionTitle,granule:g.title,start_timestamp:g.start,end_timestamp:g.end,satellite:g.platform,data_cycle:g.dataCycle,source_url:g.url||''}));metrics();E.downloadManifestBtn.disabled=!S.manifest.length;await convertAll();E.downloadCsvBtn.disabled=!(S.rows.length||S.ground.length);status(E.fetchStatus,'Finished: '+S.granules.length+' granules, '+S.rows.length.toLocaleString()+' converted value rows.',S.granules.length?'ok':'error')}catch(e){status(E.fetchStatus,'Granule fetch failed: '+e.message,'error');log(e.stack||e.message,'error')}finally{E.fetchBtn.disabled=S.selected.size===0}}
function metrics(){const a=[['Collections',S.selected.size],['Granules',S.granules.length],['Satellite rows',S.rows.length.toLocaleString()],['Ground rows',S.ground.length.toLocaleString()]];E.metrics.innerHTML=a.map(x=>'<div class="metric"><strong>'+x[1]+'</strong><span>'+x[0]+'</span></div>').join('')}
function kind(url,ct){const p=(new URL(url)).pathname.toLowerCase(),s=p+' '+(ct||'').toLowerCase();if(/csv|text\\/csv/.test(s))return'csv';if(/geojson|json/.test(s))return'json';if(/\\.tif(f)?$|geotiff|image\\/tiff/.test(s))return'geotiff';if(/\\.nc$|netcdf/.test(s))return'netcdf';if(/\\.h5$|\\.hdf5$|\\.he5$|\\.nc4$|hdf/.test(s))return'hdf';return'binary'}
async function downloadGranule(g){if(!g.url)throw new Error('No downloadable URL found in CMR metadata.');let r=await fetch(g.url,{headers:{Authorization:'Bearer '+S.token},redirect:'follow'});if(!r.ok)r=await fetch(g.url,{redirect:'follow'});if(!r.ok)throw new Error('Download HTTP '+r.status);return r}
async function convertAll(){const q=S.granules.slice(0,50);if(S.granules.length>50)log('Browser safety limit: converting first 50 granules. Manifest includes all '+S.granules.length+'.');for(let i=0;i<q.length;i++){const g=q[i],t=performance.now();try{const r=await downloadGranule(g),k=kind(g.url,r.headers.get('content-type'));let rows=[];if(k==='geotiff')rows=await tif(await r.arrayBuffer(),g);else if(k==='netcdf')rows=await nc(await r.arrayBuffer(),g);else if(k==='csv')rows=csv(await r.text(),g);else if(k==='json')rows=jsonRows(await r.json(),g);else if(k==='hdf')throw new Error('HDF5/HE5/NC4 needs a server-side HDF5 runtime; source granule is preserved in the manifest.');else throw new Error('Unsupported binary format for safe browser conversion; source granule is preserved in the manifest.');S.rows.push.apply(S.rows,rows);log(g.title+': '+rows.length.toLocaleString()+' rows converted in '+Math.round(performance.now()-t)+' ms','ok')}catch(e){log(g.title+': '+e.message,'error')}metrics();await new Promise(r=>setTimeout(r,0))}}
function base(g){const ts=g.start||g.end||'';return{latitude:'',longitude:'',timestamp:ts,date:ts?ts.slice(0,10):'',value:'',variable:S.search.component,unit:'',satellite:g.platform,collection:g.collectionShortName,granule:g.title,data_cycle:g.dataCycle,source:'NASA Earthdata',source_url:g.url||''}}
async function tif(buf,g){if(!globalThis.GeoTIFF)throw new Error('GeoTIFF library did not load');const t=await globalThis.GeoTIFF.fromArrayBuffer(buf),im=await t.getImage(),rs=await im.readRasters(),bb=im.getBoundingBox(),w=im.getWidth(),h=im.getHeight(),dx=(bb[2]-bb[0])/w,dy=(bb[3]-bb[1])/h,out=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const idx=y*w+x,lat=bb[3]-(y+.5)*dy,lon=bb[0]+(x+.5)*dx;for(let b=0;b<rs.length;b++){const v=rs[b][idx];if(Number.isFinite(v))out.push(Object.assign(base(g),{latitude:lat,longitude:lon,value:v,variable:rs.length>1?S.search.component+'_band_'+(b+1):S.search.component}))}}return out}
function findVar(r,names){const vs=r.variables||[],lo=names.map(x=>x.toLowerCase());return vs.find(v=>lo.includes(String(v.name).toLowerCase()))||vs.find(v=>lo.some(n=>String(v.name).toLowerCase().includes(n)))}
async function nc(buf,g){const R=globalThis.NetCDFReader||(globalThis.netcdfjs&&globalThis.netcdfjs.NetCDFReader);if(!R)throw new Error('NetCDF library did not load');let r;try{r=new R(buf)}catch(e){throw new Error('This file uses HDF5/NetCDF4 encoding; browser parser supports NetCDF classic only.')}const la=findVar(r,['lat','latitude','y']),lo=findVar(r,['lon','longitude','x']);if(!la||!lo)throw new Error('Latitude/longitude variables were not found.');const lat=Array.from(r.getDataVariable(la.name)),lon=Array.from(r.getDataVariable(lo.name)),skip=new Set([la.name,lo.name,'time','timestamp']),vs=(r.variables||[]).filter(v=>!skip.has(v.name)&&!/^crs|bounds?|quality|qa/i.test(v.name)),out=[];for(const v of vs){let d;try{d=Array.from(r.getDataVariable(v.name))}catch(e){continue}if(lat.length*lon.length===d.length){for(let i=0;i<lat.length;i++)for(let j=0;j<lon.length;j++){const x=d[i*lon.length+j];if(Number.isFinite(x))out.push(Object.assign(base(g),{latitude:lat[i],longitude:lon[j],value:x,variable:v.name}))}}else if(lat.length===lon.length&&lon.length===d.length){for(let i=0;i<d.length;i++){const x=d[i];if(Number.isFinite(x))out.push(Object.assign(base(g),{latitude:lat[i],longitude:lon[i],value:x,variable:v.name}))}}}if(!out.length)throw new Error('No coordinate-aligned numeric variable could be safely normalized.');return out}
function csvLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'&&q){cur+='"';i++}else if(ch==='"')q=!q;else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out}
function csv(text,g){const lines=text.replace(/^﻿/,'').split(/?
/).filter(Boolean);if(lines.length<2)throw new Error('CSV has no data rows.');const h=csvLine(lines[0]).map(x=>x.trim()),find=re=>h.findIndex(x=>re.test(x)),ilat=find(/^lat(itude)?$/i),ilon=find(/^lon(gitude)?$/i),it=find(/time|date/i),needle=S.search.component.toLowerCase(),iv=h.findIndex(x=>x.toLowerCase().includes(needle)),out=[];for(const line of lines.slice(1)){const a=csvLine(line),lat=ilat>=0?Number(a[ilat]):'',lon=ilon>=0?Number(a[ilon]):'',ts=it>=0?a[it]:(g.start||'');if(iv>=0){const v=Number(a[iv]);if(Number.isFinite(v))out.push(Object.assign(base(g),{latitude:lat,longitude:lon,timestamp:ts,date:String(ts).slice(0,10),value:v,variable:h[iv]}))}else h.forEach((name,i)=>{if([ilat,ilon,it].includes(i))return;const v=Number(a[i]);if(Number.isFinite(v))out.push(Object.assign(base(g),{latitude:lat,longitude:lon,timestamp:ts,date:String(ts).slice(0,10),value:v,variable:name}))})}return out}
function jsonRows(j,g){const out=[];if(Array.isArray(j&&j.features)){for(const f of j.features){const c=f&&f.geometry&&f.geometry.coordinates;if(f&&f.geometry&&f.geometry.type==='Point'&&Array.isArray(c))for(const kv of Object.entries(f.properties||{})){const v=Number(kv[1]);if(Number.isFinite(v))out.push(Object.assign(base(g),{longitude:c[0],latitude:c[1],value:v,variable:kv[0]}))}}}else if(Array.isArray(j)){for(const o of j){const lat=Number(o.latitude??o.lat),lon=Number(o.longitude??o.lon??o.lng),ts=o.timestamp??o.datetime??o.date??g.start;for(const kv of Object.entries(o)){if(['latitude','lat','longitude','lon','lng','timestamp','datetime','date'].includes(kv[0]))continue;const v=Number(kv[1]);if(Number.isFinite(v))out.push(Object.assign(base(g),{latitude:lat,longitude:lon,timestamp:ts,date:String(ts||'').slice(0,10),value:v,variable:kv[0]}))}}}if(!out.length)throw new Error('JSON structure has no safely identifiable coordinate/value rows.');return out}
function toCsv(rows){const cols=['latitude','longitude','timestamp','date','value','variable','unit','satellite','collection','granule','data_cycle','source','source_url'],q=v=>{const s=v==null?'':String(v);return /[",
]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};return[cols.join(',')].concat(rows.map(r=>cols.map(c=>q(r[c])).join(','))).join('
')}
function save(name,text,type){const b=new Blob([text],{type:type||'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function aliases(q){const s=q.toLowerCase().replace(/[^a-z0-9.]/g,''),m={'pm2.5':['pm25','pm2.5','pm2_5'],'pm25':['pm25','pm2.5','pm2_5'],'pm10':['pm10'],'no2':['no2','nitrogendioxide'],'o3':['o3','ozone'],'so2':['so2','sulfurdioxide'],'co':['co','carbonmonoxide'],'bc':['bc','blackcarbon']};return m[s]||[s]}
async function aq(path,p){const key=E.openAqKey.value.trim()||S.aq;if(!key)throw new Error('OpenAQ API key is required.');const u=new URLSearchParams();Object.entries(p||{}).forEach(kv=>{if(kv[1]!==undefined&&kv[1]!==null&&kv[1]!=='')u.set(kv[0],String(kv[1]))});const r=await fetch(OPENAQ+path+'?'+u.toString(),{headers:{'X-API-Key':key}});if(!r.ok)throw new Error('OpenAQ '+r.status+': '+await r.text().catch(()=>r.statusText));return r.json()}
async function ground(){if(!S.search)return;S.aq=E.openAqKey.value.trim();if(S.aq)sessionStorage.setItem('openAqKey',S.aq);E.groundBtn.disabled=true;S.ground=[];E.groundSummary.innerHTML='';status(E.groundStatus,'Finding matching OpenAQ parameter and stations…');try{const ps=await aq('/parameters',{limit:1000,page:1}),al=aliases(S.search.component),matched=(ps.results||[]).filter(p=>{const h=((p.name||'')+' '+(p.displayName||'')).toLowerCase().replace(/[^a-z0-9.]/g,'');return al.some(a=>h.includes(a.replace(/[^a-z0-9.]/g,'')))});if(!matched.length)throw new Error('This component has no matching OpenAQ parameter. OpenAQ mainly covers ground-level air-quality measurements.');const param=matched[0],box=bbox(S.search.geometry).map(x=>Number(x.toFixed(4))).join(','),ld=await aq('/locations',{bbox:box,parameters_id:param.id,limit:100,page:1}),locs=ld.results||[];if(!locs.length)throw new Error('No OpenAQ stations found inside this area for the selected component.');let sc=0;for(const loc of locs.slice(0,30)){const sd=await aq('/locations/'+loc.id+'/sensors',{limit:100,page:1}),ss=(sd.results||[]).filter(s=>s.parameter&&s.parameter.id===param.id);for(const sen of ss.slice(0,10)){sc++;for(let page=1;page<=20;page++){const md=await aq('/sensors/'+sen.id+'/measurements',{datetime_from:isoStart(S.search.start),datetime_to:isoEnd(S.search.end),limit:1000,page:page}),rr=md.results||[];for(const m of rr){const ts=(m.period&&m.period.datetimeFrom&&m.period.datetimeFrom.utc)||(m.datetime&&m.datetime.utc)||(m.datetimeFrom&&m.datetimeFrom.utc)||'',lat=(m.coordinates&&m.coordinates.latitude)??(loc.coordinates&&loc.coordinates.latitude)??'',lon=(m.coordinates&&m.coordinates.longitude)??(loc.coordinates&&loc.coordinates.longitude)??'';S.ground.push({latitude:lat,longitude:lon,timestamp:ts,date:String(ts).slice(0,10),value:m.value??(m.summary&&m.summary.avg)??'',variable:(sen.parameter&&sen.parameter.name)||param.name||S.search.component,unit:(sen.parameter&&sen.parameter.units)||param.units||'',satellite:'GROUND_SENSOR',collection:'OpenAQ location '+loc.id,granule:'sensor '+sen.id,data_cycle:'measurement',source:'OpenAQ',source_url:OPENAQ+'/sensors/'+sen.id+'/measurements'})}if(rr.length<1000)break}}}metrics();E.groundSummary.innerHTML='<div class="ground-row"><strong>Parameter</strong><span>'+esc(param.displayName||param.name)+'</span><strong>Stations</strong><span>'+locs.length+'</span></div><div class="ground-row"><strong>Sensors queried</strong><span>'+sc+'</span><strong>Measurements</strong><span>'+S.ground.length.toLocaleString()+'</span></div>';status(E.groundStatus,'Fetched '+S.ground.length.toLocaleString()+' ground measurements.',S.ground.length?'ok':'error');if(S.ground.length)E.downloadCsvBtn.disabled=false}catch(e){status(E.groundStatus,e.message,'error')}finally{E.groundBtn.disabled=false}}
E.verifyTokenBtn.onclick=verify;E.forgetSecretsBtn.onclick=forget;E.geometryType.onchange=geomUI;E.searchBtn.onclick=search;E.collectionFilter.oninput=render;E.selectAllBtn.onclick=()=>{const q=E.collectionFilter.value.trim().toLowerCase();S.collections.filter(c=>[c.title,c.shortName,c.provider].concat(c.platforms).join(' ').toLowerCase().includes(q)).forEach(c=>S.selected.add(c.id));render();E.fetchBtn.disabled=S.selected.size===0};E.clearAllBtn.onclick=()=>{S.selected.clear();render();E.fetchBtn.disabled=true};E.fetchBtn.onclick=fetchSelected;E.groundBtn.onclick=ground;E.downloadManifestBtn.onclick=()=>save('earthdata_granule_manifest.json',JSON.stringify(S.manifest,null,2),'application/json');E.downloadCsvBtn.onclick=()=>{const all=S.rows.concat(S.ground),n='earthdata_'+S.search.component.replace(/[^a-z0-9]+/gi,'_')+'_'+S.search.start+'_to_'+S.search.end+'.csv';save(n,toCsv(all),'text/csv')};
geomUI();metrics();if(S.token)status(E.verifyStatus,'A token exists in this browser session. Verify it to continue.');
