const CDN={
  geotiff:'https://cdn.jsdelivr.net/npm/geotiff@2.1.3/+esm',
  netcdf:'https://cdn.jsdelivr.net/npm/netcdfjs@3.0.0/+esm',
  h5wasm:'https://cdn.jsdelivr.net/npm/h5wasm@0.10.3/dist/esm/hdf5_hl.js'
};

function base(g,component){const ts=g.start||g.end||'';return{latitude:'',longitude:'',timestamp:ts,date:ts?ts.slice(0,10):'',value:'',variable:g.assetVariable||component,unit:g.assetUnit||'',satellite:g.platform,collection:g.collectionShortName,granule:g.title,data_cycle:g.dataCycle,source:g.sourceLabel||'NASA Earthdata',source_url:g.provenanceUrl||g.url||''}}
function haversineMeters(aLat,aLon,bLat,bLon){const R=6371008.8,toRad=x=>x*Math.PI/180,dLat=toRad(bLat-aLat),dLon=toRad(bLon-aLon),p=Math.sin(dLat/2)**2+Math.cos(toRad(aLat))*Math.cos(toRad(bLat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(p)))}
function pointInPolygon(lon,lat,v){let inside=false;for(let i=0,j=v.length-2;i<v.length;i+=2){const xi=v[i],yi=v[i+1],xj=v[j],yj=v[j+1],cross=((yi>lat)!==(yj>lat))&&(lon<(xj-xi)*(lat-yi)/(yj-yi||Number.EPSILON)+xi);if(cross)inside=!inside;j=i}return inside}
function pointToSegmentMeters(lat,lon,aLat,aLon,bLat,bLon){const clat=(aLat+bLat+lat)/3*Math.PI/180,kx=111320*Math.cos(clat),ky=111320,px=lon*kx,py=lat*ky,ax=aLon*kx,ay=aLat*ky,bx=bLon*kx,by=bLat*ky,dx=bx-ax,dy=by-ay,t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy))}
function inferredGridBuffer(rows){const pts=rows.filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))).slice(0,400),d=[];for(let i=1;i<pts.length;i++){const x=haversineMeters(Number(pts[i-1].latitude),Number(pts[i-1].longitude),Number(pts[i].latitude),Number(pts[i].longitude));if(x>10&&x<500000)d.push(x)}if(!d.length)return 15000;d.sort((a,b)=>a-b);return Math.max(500,Math.min(50000,d[Math.floor(d.length/2)]*.6))}
function clipRows(rows,g){if(!g||!rows.length)return rows;const good=rows.filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude)));if(!good.length)return[];const v=g.values;if(g.type==='bbox')return good.filter(r=>{const lat=Number(r.latitude),lon=Number(r.longitude);return lon>=v[0]&&lon<=v[2]&&lat>=v[1]&&lat<=v[3]});if(g.type==='circle')return good.filter(r=>haversineMeters(v[1],v[0],Number(r.latitude),Number(r.longitude))<=v[2]);if(g.type==='polygon')return good.filter(r=>pointInPolygon(Number(r.longitude),Number(r.latitude),v));if(g.type==='point'){const byVar=new Map();for(const r of good){const d=haversineMeters(v[1],v[0],Number(r.latitude),Number(r.longitude)),key=String(r.variable||'value'),prev=byVar.get(key);if(!prev||d<prev.d)byVar.set(key,{d,r})}return Array.from(byVar.values()).map(x=>x.r)}if(g.type==='line'){const buffer=inferredGridBuffer(good);return good.filter(r=>{const lat=Number(r.latitude),lon=Number(r.longitude);for(let i=0;i<v.length-2;i+=2)if(pointToSegmentMeters(lat,lon,v[i+1],v[i],v[i+3],v[i+2])<=buffer)return true;return false})}return good}
function findVar(r,names){const vs=r.variables||[],lo=names.map(x=>x.toLowerCase());return vs.find(v=>lo.includes(String(v.name).toLowerCase()))||vs.find(v=>lo.some(n=>String(v.name).toLowerCase().includes(n)))}
function ncAttr(v,names){const a=(v&&v.attributes)||[];for(const n of names){const x=a.find(q=>String(q.name||'').toLowerCase()===n.toLowerCase());if(x){const z=x.value;return Array.isArray(z)||ArrayBuffer.isView(z)?z[0]:z}}return undefined}
function packedValue(raw,meta){const x=Number(raw);if(!Number.isFinite(x))return null;const fills=[ncAttr(meta,['_FillValue']),ncAttr(meta,['missing_value'])].filter(v=>v!==undefined).map(Number);if(fills.some(v=>Number.isFinite(v)&&x===v))return null;const min=Number(ncAttr(meta,['valid_min'])),max=Number(ncAttr(meta,['valid_max']));if(Number.isFinite(min)&&x<min)return null;if(Number.isFinite(max)&&x>max)return null;const scale=Number(ncAttr(meta,['scale_factor'])),offset=Number(ncAttr(meta,['add_offset']));const y=x*(Number.isFinite(scale)?scale:1)+(Number.isFinite(offset)?offset:0);return Number.isFinite(y)?y:null}
function preferredVars(vs,wants){const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,''),bad=/quality|flag|qa|uncert|precision|error|cloud|angle|pressure|terrain|rowanomaly|weight|corner|bounds?/i,direct=vs.filter(v=>wants.some(w=>w&&norm(v.name).includes(w))&&!bad.test(String(v.name)));return direct.length?direct:vs.filter(v=>!bad.test(String(v.name)))}
function h5Attr(obj,names){const attrs=obj&&obj.attrs;if(!attrs)return undefined;const keys=Object.keys(attrs);for(const n of names){const k=keys.find(x=>x.toLowerCase()===n.toLowerCase());if(k){const a=attrs[k],v=a&&Object.prototype.hasOwnProperty.call(a,'value')?a.value:a;return Array.isArray(v)||ArrayBuffer.isView(v)?v[0]:v}}return undefined}
function h5Packed(raw,obj){const x=Number(raw);if(!Number.isFinite(x))return null;const fills=[h5Attr(obj,['_FillValue']),h5Attr(obj,['missing_value'])].filter(v=>v!==undefined).map(Number);if(fills.some(v=>Number.isFinite(v)&&x===v))return null;const min=Number(h5Attr(obj,['valid_min'])),max=Number(h5Attr(obj,['valid_max']));if(Number.isFinite(min)&&x<min)return null;if(Number.isFinite(max)&&x>max)return null;const scale=Number(h5Attr(obj,['scale_factor'])),offset=Number(h5Attr(obj,['add_offset']));const y=x*(Number.isFinite(scale)?scale:1)+(Number.isFinite(offset)?offset:0);return Number.isFinite(y)?y:null}
function csvLine(s){const out=[];let cur='',q=false;for(let i=0;i<s.length;i++){const ch=s[i];if(ch==='"'){if(q&&s[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out}

async function parseTif(buf,g,component){const GeoTIFF=await import(CDN.geotiff);const t=await GeoTIFF.fromArrayBuffer(buf),im=await t.getImage(),rs=await im.readRasters(),bb=im.getBoundingBox(),keys=im.getGeoKeys?im.getGeoKeys():{},nativeNoData=im.getGDALNoData?Number(im.getGDALNoData()):NaN,w=im.getWidth(),h=im.getHeight(),dx=(bb[2]-bb[0])/w,dy=(bb[3]-bb[1])/h,out=[];const projected=Number(keys.ProjectedCSTypeGeoKey||0),geographic=Number(keys.GeographicTypeGeoKey||0),looksDegrees=Math.abs(bb[0])<=180&&Math.abs(bb[2])<=180&&Math.abs(bb[1])<=90&&Math.abs(bb[3])<=90,scale=Number.isFinite(Number(g.assetScale))?Number(g.assetScale):1,offset=Number.isFinite(Number(g.assetOffset))?Number(g.assetOffset):0,noData=Number.isFinite(Number(g.assetNoData))?Number(g.assetNoData):nativeNoData,inv3857=(x,y)=>{const lon=x/20037508.34*180,lat=180/Math.PI*(2*Math.atan(Math.exp((y/20037508.34*180)*Math.PI/180))-Math.PI/2);return[lon,lat]},invModis=(x,y)=>{const R=6371007.181,latRad=y/R,lat=latRad*180/Math.PI,cos=Math.cos(latRad),lon=Math.abs(cos)<1e-12?NaN:(x/(R*cos))*180/Math.PI;return[lon,lat]},hint=String(g.crsHint||'').toLowerCase(),useModis=hint==='modis_sinusoidal'&&!looksDegrees;if(!hint&&projected&&projected!==3857)throw new Error('Projected GeoTIFF EPSG:'+projected+' cannot be converted safely without a CRS definition.');for(let y=0;y<h;y++)for(let x=0;x<w;x++){const idx=y*w+x,rawY=bb[3]-(y+.5)*dy,rawX=bb[0]+(x+.5)*dx,ll=useModis?invModis(rawX,rawY):(projected===3857?inv3857(rawX,rawY):[rawX,rawY]),lon=ll[0],lat=ll[1];if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;if(!hint&&!projected&&geographic&&geographic!==4326&&geographic!==4269)throw new Error('Geographic GeoTIFF EPSG:'+geographic+' is not safely supported.');for(let b=0;b<rs.length;b++){const raw=Number(rs[b][idx]);if(!Number.isFinite(raw)||(Number.isFinite(noData)&&raw===noData))continue;const v=raw*scale+offset;if(Number.isFinite(v))out.push(Object.assign(base(g,component),{latitude:lat,longitude:lon,value:v,variable:g.assetVariable||(rs.length>1?component+'_band_'+(b+1):component),unit:g.assetUnit||''}))}}return out}

async function parseNc(buf,g,component,wants){const mod=await import(CDN.netcdf),R=mod.NetCDFReader;if(!R)throw new Error('NetCDF parser could not be loaded');let r;try{r=new R(buf)}catch(e){return parseHdf5(buf,g,component,wants)}const la=findVar(r,['lat','latitude']),lo=findVar(r,['lon','longitude']);if(!la||!lo)throw new Error('Latitude/longitude variables were not found.');const lat=Array.from(r.getDataVariable(la.name)),lon=Array.from(r.getDataVariable(lo.name)),skip=new Set([la.name,lo.name,'time','timestamp']),all=(r.variables||[]).filter(v=>!skip.has(v.name)&&!/^crs|bounds?$/i.test(v.name)),vs=preferredVars(all,wants),out=[];for(const v of vs){let d;try{d=Array.from(r.getDataVariable(v.name))}catch(e){continue}const unit=String(ncAttr(v,['units'])||'');if(lat.length*lon.length===d.length){for(let i=0;i<lat.length;i++)for(let j=0;j<lon.length;j++){const x=packedValue(d[i*lon.length+j],v),laa=packedValue(lat[i],la),loo=packedValue(lon[j],lo);if(x!==null&&laa!==null&&loo!==null&&Number.isFinite(laa)&&Number.isFinite(loo))out.push(Object.assign(base(g,component),{latitude:laa,longitude:loo,value:x,variable:v.name,unit}))}}else if(lat.length===lon.length&&lon.length===d.length){for(let i=0;i<d.length;i++){const x=packedValue(d[i],v),laa=packedValue(lat[i],la),loo=packedValue(lon[i],lo);if(x!==null&&laa!==null&&loo!==null&&Number.isFinite(laa)&&Number.isFinite(loo))out.push(Object.assign(base(g,component),{latitude:laa,longitude:loo,value:x,variable:v.name,unit}))}}}if(!out.length)throw new Error('No coordinate-aligned numeric component variable could be safely normalized.');return out}

async function parseHdf5(buf,g,component,wants){const mod=await import(CDN.h5wasm),h5=mod.default;if(!h5)throw new Error('HDF5 WebAssembly parser could not be loaded');const ready=await h5.ready,FS=ready.FS,name='/granule_'+Date.now()+'_'+Math.floor(Math.random()*1000000)+'.h5';FS.writeFile(name,new Uint8Array(buf));let file;try{file=new h5.File(name,'r');const sets=[],walk=(group,path)=>{for(const key of group.keys()){const p=path?path+'/'+key:key;let obj;try{obj=file.get(p)}catch(e){continue}if(obj&&typeof obj.keys==='function')walk(obj,p);else if(obj&&Object.prototype.hasOwnProperty.call(obj,'value'))sets.push({path:p,obj})}};walk(file,'');const flat=v=>ArrayBuffer.isView(v)?Array.from(v):(Array.isArray(v)?v.flat(Infinity):[v]),leaf=p=>p.split('/').pop().toLowerCase(),norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');const latSet=sets.find(s=>['lat','latitude','latitudes'].includes(norm(leaf(s.path)))),lonSet=sets.find(s=>['lon','lng','longitude','longitudes'].includes(norm(leaf(s.path))));if(!latSet||!lonSet)throw new Error('HDF5/NetCDF4 file has no identifiable latitude/longitude datasets.');const lat=flat(latSet.obj.value),lon=flat(lonSet.obj.value),excluded=/^(lat|latitude|latitudes|lon|lng|longitude|longitudes|time|timestamp|crs)$/i,bad=/quality|flag|qa|uncert|precision|error|cloud|angle|pressure|terrain|rowanomaly|weight|corner|bounds?/i;let vars=sets.filter(s=>!excluded.test(norm(leaf(s.path)))),matched=vars.filter(s=>wants.some(a=>a&&norm(s.path).includes(a))&&!bad.test(s.path));if(!matched.length)matched=vars.filter(s=>{if(bad.test(s.path))return false;let v;try{v=flat(s.obj.value)}catch(e){return false}return v.length===lat.length||v.length===lat.length*lon.length});if(!matched.length)throw new Error('No component dataset aligns with the source geolocation grid.');const out=[];for(const s of matched){let data;try{data=flat(s.obj.value)}catch(e){continue}const unit=String(h5Attr(s.obj,['units','unit'])||'');if(lat.length===lon.length&&data.length===lat.length){for(let i=0;i<data.length;i++){const v=h5Packed(data[i],s.obj),la=h5Packed(lat[i],latSet.obj),lo=h5Packed(lon[i],lonSet.obj);if(v!==null&&la!==null&&lo!==null&&Number.isFinite(la)&&Number.isFinite(lo))out.push(Object.assign(base(g,component),{latitude:la,longitude:lo,value:v,variable:s.path,unit}))}}else if(lat.length*lon.length===data.length){for(let i=0;i<lat.length;i++)for(let j=0;j<lon.length;j++){const v=h5Packed(data[i*lon.length+j],s.obj),la=h5Packed(lat[i],latSet.obj),lo=h5Packed(lon[j],lonSet.obj);if(v!==null&&la!==null&&lo!==null&&Number.isFinite(la)&&Number.isFinite(lo))out.push(Object.assign(base(g,component),{latitude:la,longitude:lo,value:v,variable:s.path,unit}))}}}if(!out.length)throw new Error('HDF5 component values could not be aligned without changing the source grid.');return out}finally{try{if(file)file.close()}catch(e){}try{FS.unlink(name)}catch(e){}}}

function parseCsv(buf,g,component){let raw=new TextDecoder().decode(buf);if(raw.charCodeAt(0)===65279)raw=raw.slice(1);const lines=raw.split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('CSV has no data rows.');const h=csvLine(lines[0]).map(x=>x.trim()),find=re=>h.findIndex(x=>re.test(x)),ilat=find(/^lat(itude)?$/i),ilon=find(/^lon(gitude)?$/i),it=find(/time|date/i),needle=component.toLowerCase(),iv=h.findIndex(x=>x.toLowerCase().includes(needle)),out=[];for(const line of lines.slice(1)){const row=csvLine(line),lat=ilat>=0?Number(row[ilat]):'',lon=ilon>=0?Number(row[ilon]):'',ts=it>=0?row[it]:(g.start||'');if(iv>=0){const v=Number(row[iv]);if(Number.isFinite(v))out.push(Object.assign(base(g,component),{latitude:lat,longitude:lon,timestamp:ts,date:String(ts).slice(0,10),value:v,variable:h[iv]}))}else h.forEach((name,i)=>{if([ilat,ilon,it].includes(i))return;const v=Number(row[i]);if(Number.isFinite(v))out.push(Object.assign(base(g,component),{latitude:lat,longitude:lon,timestamp:ts,date:String(ts).slice(0,10),value:v,variable:name}))})}return out}
function parseJson(buf,g,component){const j=JSON.parse(new TextDecoder().decode(buf)),out=[];if(Array.isArray(j&&j.features)){for(const f of j.features){const c=f&&f.geometry&&f.geometry.coordinates;if(f&&f.geometry&&f.geometry.type==='Point'&&Array.isArray(c))for(const kv of Object.entries(f.properties||{})){const v=Number(kv[1]);if(Number.isFinite(v))out.push(Object.assign(base(g,component),{longitude:c[0],latitude:c[1],value:v,variable:kv[0]}))}}}else if(Array.isArray(j)){for(const o of j){const lat=Number(o.latitude??o.lat),lon=Number(o.longitude??o.lon??o.lng),ts=o.timestamp??o.datetime??o.date??g.start;for(const kv of Object.entries(o)){if(['latitude','lat','longitude','lon','lng','timestamp','datetime','date'].includes(kv[0]))continue;const v=Number(kv[1]);if(Number.isFinite(v))out.push(Object.assign(base(g,component),{latitude:lat,longitude:lon,timestamp:ts,date:String(ts||'').slice(0,10),value:v,variable:kv[0]}))}}}if(!out.length)throw new Error('JSON structure has no safely identifiable coordinate/value rows.');return out}

self.onmessage=async(event)=>{const {buffer,format,granule,component,geometry,wants}=event.data;try{let rows;if(format==='geotiff')rows=await parseTif(buffer,granule,component);else if(format==='netcdf')rows=await parseNc(buffer,granule,component,wants||[]);else if(format==='hdf')rows=await parseHdf5(buffer,granule,component,wants||[]);else if(format==='csv')rows=parseCsv(buffer,granule,component);else if(format==='json')rows=parseJson(buffer,granule,component);else throw new Error('Unsupported format: '+format);const sourceRows=rows.length,clipped=clipRows(rows,geometry);self.postMessage({ok:true,rows:clipped,sourceRows});}catch(error){self.postMessage({ok:false,error:error instanceof Error?error.message:String(error)});}};
